spring:
  datasource:
    url: jdbc:postgresql://corporateorganization.postgres.database.azure.com:5432/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
producer:
  event:
    connection-string: ${EVENT_CONNECTION_STRING}
  topic:
    name: corporate-organization