spring:
  datasource:
    url: jdbc:postgresql://corporateorganization.postgres.database.azure.com:5432/postgres
producer:
  event:
    host: antharos.servicebus.windows.net
    port: 6616
    user: RootManageSharedAccessKey
  topic:
    name: corporate-organization